### ISSUE TITLE
Plan deployment environments

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#104]
Any objections / timing considerations / other thoughts on this @dabreegster ?

https://github.com/Active-Travel-England

**Comment by dabreegster** [comment]
Nope, we can do it whenever. The only practical impact will be the dev URL of the site changing from https://acteng.github.io/atip/.

**Comment by dabreegster** [comment]
A short-term plan for environments:

- atip.uk remains prod, has to be deployed manually with the `deploy_prod.sh` script in this repo. That's always done from some particular branch -- it's always been `main` so far.
- The github version auto-deployed on every commit to `main` will change URLs to the new org, but still be hosted at github.io. We're using it as a dev version right now.

So far all changes to `main` are intended for prod; they're small fixes and improvements. Once we start making big changes headed towards some kind of v2, we may not want people using prod to see them yet. We have a few options.

1) Develop big new features in a long-term `v2` branch. Open PRs against that branch. Keep `main` for important fixes to prod that we need to deploy.
2) Invert it, start a long-term `v1-backports` branch. Always deploy prod from there. `main` becomes the development version, and we cherrypick fixes to `v1-backports`.
3) Only have one long-term branch, `main`, and deploy prod from there. But any new big new features, "feature guard" or "experiment flag" guard them. We can plumb through environment variables through Vite to say if we're prod or not, and in the code, literally have `if (prod) { ... } else { ... }` when needed. We can even make up URL query parameters to opt into experiments at runtime. Depending on the changes we're making, this could get complex to reason about, because the way two components wire together might change dramatically. If it's simple stuff like v2 having a new button, hiding it in v1/prod based on a feature guard is easy.

Another trick that may come in handy: when we deploy the github version automatically on a push, we can deploy multiple copies of the site, even from multiple branches. Something like `https://acteng.github.io/atip/` for the main branch, `https://acteng.github.io/atip/v2-experiment` that uses a different branch, etc.

Thoughts, @Sparrow0hawk? So far all the changes we're making could go to prod today, but that'll change pretty soon -- we're expanding the schema and adding new forms.

**Comment by Sparrow0hawk** [comment]
My inclination is to go via route 2
> Invert it, start a long-term v1-backports branch. Always deploy prod from there. main becomes the development version, and we cherrypick fixes to v1-backports.

My personal opinion is `main` should always be the most up to date, working version (but that's purely opinion based). We definitely should have multiple deployments setup so we can test experimental changes in a deployment-like context so i'm a fan of:
> Another trick that may come in handy: when we deploy the github version automatically on a push, we can deploy multiple copies of the site, even from multiple branches. Something like https://acteng.github.io/atip/ for the main branch, https://acteng.github.io/atip/v2-experiment that uses a different branch, etc.

I think around that is probably also determining process for sign off for deployment from `main` to prod and can we automate that to some extent via a `v1-backports` branch?

**Comment by dabreegster** [comment]
https://github.com/acteng/atip/issues/107#issuecomment-1493284885
Moving discussion of keeping v1 forever alive to here

**Comment by dabreegster** [comment]
I have an immediate need to share the in-progress PR with inspections, so just modified the github workflow to deploy that branch alongside `main` on github pages. It'd actually be awesome to auto-deploy every PR in this way, with the branch name in the URL. Adding that to the wishlist...

**Comment by Sparrow0hawk** [comment]
> It'd actually be awesome to auto-deploy every PR in this way, with the branch name in the URL.

Sounds up my street. Let me have a play

**Comment by dabreegster** [comment]
@Sparrow0hawk, I think I got auto deployment of all branches working (after many rounds and copious chatgpt help): https://github.com/acteng/atip/blob/main/.github/workflows/web.yml

These're all live now:
- https://acteng.github.io/atip/scheme.html?authority=West%20of%20England%20Combined%20Authority
- https://acteng.github.io/atip/tooltip/scheme.html?authority=West%20of%20England%20Combined%20Authority
- https://acteng.github.io/atip/split_line/scheme.html?authority=West%20of%20England%20Combined%20Authority
- https://acteng.github.io/atip/draw_controls_from_scratch/scheme.html?authority=West%20of%20England%20Combined%20Authority

**Comment by dabreegster** [comment]
... possibly with some funniness. That first link appears to have grabbed the `split_line` branch, not main.

Also, the `checkout` with `force-depth: 0` step could grow larger and larger over time, since it fetches all history, including the ever-growing `gh-pages` branch

**Comment by robinlovelace-ate** [comment]
So cool, and useful!

**Comment by dabreegster** [comment]
https://github.com/acteng/atip/actions/runs/4924814203/jobs/8798294598

Just noting a bug with the current deployment config. When the action is triggered by a branch that's broken, the whole thing fails. Also it incorrectly counts as the main branch... possibly the "main" branch deployed has been the latest one to trigger the workflow!

Looking at https://github.com/acteng/atip/blob/bb6d4a9fc0f0774e656c4c64d57de3cee7d8db15/.github/workflows/web.yml#L23, yeah, this is wrong. I think we can just remove this step and modify the one below to include `main`. And rename it so that it isn't nested under a subdirectory like the other branches

**Comment by robinlovelace-ate** [comment]
Closing as this has been done, branches go to URLs with different experiments.
