### ISSUE TITLE
Couldn't load scheme from a file:

### ISSUE THREAD

**Issue by buildvoc10** [acteng/atip#135]
Hello getting a error Couldn't load scheme from a file: TypeError: Cannot read properties of null (reading 'length_meters')
![image](https://user-images.githubusercontent.com/76884997/233919294-bf53d891-4b81-42ab-a67d-667d3d78a42f.png)

see example https://github.com/buildvoc/buildingshistory/blob/main/geojson-examples/Farnham-Park-Long-Walk.geojson

**Comment by dabreegster** [comment]
Thanks for reporting! It looks like JOSM sets `"properties": null`, which we didn't expect. We can fix this in the backfill stage. I'm not sure if it's valid GeoJSON or not to explicitly set it to null (rather than just omit the key/value entirely), but if a major tool is producing it, we should fix

**Comment by dabreegster** [comment]
This specific problem should be fixed. #65 is still open for more general handling of inputs from tools besides ATIP.
