### ISSUE TITLE
Adding a layer for schools and other POIs

### ISSUE THREAD

**Issue by dabreegster** [acteng/atip#235]
An idea is to show more optional contextual layers in ATIP, to help both inspections and TAs understand the relation between key trip origins/destinations and where infrastructure is proposed. To be specific, imagine:

- A toggleable layer in ATIP, showing the location of schools. Hover or click to see more information (name, grades/age ranges, capacity, other ideas from https://www.openstreetmap.org/way/80278348)
- Some tool in ATIP that lets you measure the distance (as the crow flies, or through the transport network) between interventions and some destinations that the user specifies
- Both of these could be relevant both in the per-scheme editing and the new browse scheme page

I don't know how important this idea is to prioritize, or what specific requirements/requests would be -- so this issue is to start that discussion. Some possible questions:

- What categories of things are most important to see? Schools, healthcare, childcare, parks/sports/active leisure facilities, etc?
- What info do we want to surface about these places? Do we want to use OSM, or are there non-public data sources with more info about routes?
- What amount of spatial information is useful to show? I have previously modeled POIs at the building level, like https://www.openstreetmap.org/way/969477716 and https://www.openstreetmap.org/way/969477717, but in hindsight, this may be unnecessary. A (possibly large) polygon or multipolygon like https://www.openstreetmap.org/way/80278348 or https://www.openstreetmap.org/way/84656164 representing an entire campus with many buildings may be simpler and serve the same purpose.

**Comment by robinlovelace-ate** [comment]
Good idea and lots of options. Knowing how many trip attractors a proposed intervention passes by would be super helpful for on-the-fly thinking about possibly levels of usage, although there is a slight danger of a self reinforcing trend: places with existing good place-making characteristics that already have lots of facilities could end up being rated higher. If we're going to add a layer for other POIs, in addition to transport network info such as the already-implemented speed limit layer, which is really valuable, I wonder if adding information on the number of people who live within x m of the intervention would be a lower hanging fruit? Lots of good data on where people are and links back to previous ideas discussed Dustin.

 I think in terms of priorities points that relate to the transport network such as bus stops, cycle parking, amenities along routes such as parks, and cafes/pubs could be a low hanging fruit. There is an excellent open access dataset on schools so I would use that rather than data from OSM which is unfortunately inconsistent and infrequently updated in many parts of England.

Datasets on publicly owned trip attractors like schools, leisure centres and healthcare facilities are available outside OSM so I would prioritise stuff like parks (there is OS's green spaces dataset which is open), scenic routes and other things that are good on OSM about which we don't have great open data.

**Comment by dabreegster** [comment]
Duplicate of #284. In the short term, we'll just get these as view-only layers. "X resources / total people within Y minutes walks of an intervention" can happen later on
