### ISSUE TITLE
Handling schema changes mid-edit

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#254]
I know the schema dropdown is experimental but still think it's worth exploring:

- [ ] Worth notifying users that their edits will re-appear when they go back to the schema in which edits were made if they change schema after adding objects?
- [ ] Can objects edited with one schema be imported into a session that is using a different schema (I guess I should try, writing in haste sorry)?

**Comment by dabreegster** [comment]
Re-thinking the schema dropdown, maybe it better belongs as a big modal that lists the other schemas, describes their purpose, and makes it clear the entire page/app is about to change substantially. Or maybe we don't even have a dropdown, and direct people for each use case using a URL we manually give them right now.

> Worth notifying users that their edits will re-appear

It could be. Similar to how "clear all" today has a confirmation modal, we could use this as a place to let people know what's going on.

> Can objects edited with one schema be imported into a session that is using a different schema

No, by design, because the attributes per object are different. No known use case for doing this yet.

**Comment by robinlovelace-ate** [comment]
> Or maybe we don't even have a dropdown, and direct people for each use case using a URL we manually give them right now.

That one sounds better to me at this stage: each use case is so domain specific it deserves its own URL and I can rarely/ever imagine users needing to switch mid edits. So big +1 to encoding schema in URL not dropdown from me.

**Comment by robinlovelace-ate** [comment]
That would fix the issue for me. I think there may still need to be documentation and defensive programming that catches situations in which people accidentally try to upload edits made in one schema to another but that's probably capture in another issue. Another thing I like about the URL-based schema selection: simpler UX and hides away that dropdown that can could cause confusion.

**Comment by robinlovelace-ate** [comment]
Yes there should be a heading, e.g. "Scheme design mode", "Development planning mode", "Critical issue mode", "Experimental mode" where we can test solutions to #231
