### ISSUE TITLE
Differentiating Between LCWIPs/schemes on browse page

### ISSUE THREAD

**Issue by Pete-Y-CS** [acteng/atip#445]
At a glance, and even possibly with close inspection it's not possible to differentiate between which features belong to which scheme/LCWIP.

We have a 'bounding polygon' tag you can apply to polygons drawn in the sketcher. Maybe we want to encourage the use of this and make it used by the browse page?

I'm sure there are plenty of other options for this too.

**Comment by Pete-Y-CS** [comment]
Maybe we want to revisit the idea of a 3 tier system: superschemes/LCWIPs, schemes, interventions. Thiscould be reintroduced by putting all schemes from a file into a single superscheme @dabreegster

**Comment by dabreegster** [comment]
The boundary polygons have caused UX problems in the past; I'm not sure about encouraging more. https://github.com/acteng/atip/blob/a965c5baf86e6d7a66d570f77a1e428fbbceccce/src/lib/browse/data.ts#L44
If we had confidence the boundary polygons wouldn't overlap, we could render them as non-interactive objects and style clearly as boundaries using dashed lines. But also, manually drawing these sounds tedious and ripe for inconsistencies. We could calculate convex or concave hulls and see if that helps? Or do some kind of KNN matching.

As a brute force thing to try, we could color every scheme a different color. Since there's too many, we could cycle through just some colors, but try to use different colors for adjacent schemes.

Maybe in the initial tooltips, we could emphasize scheme too, not just feature name.

I don't understand the superscheme idea. We have many schemes (both from LCWIPs and other sources) next to each other on the map, and visually distinguishing them is hard -- that's the root problem we've got?

**Comment by Pete-Y-CS** [comment]
> Hi, stupid question but the black lines are obviously routes included as part of different LCWIPs, however, is there are demarcation for the actual LCWIPs themselves? i.e. something to track which routes belong to which LCWIPs/any geographic demarcation of which LCWIPs are where?

> I ask as it would be useful to denote which schemes belong to which LCWIPs

**Comment by Pete-Y-CS** [comment]
Just putting the specific ask here for more context
