### ISSUE TITLE
Button to add additional non-ATIP generated data layers

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#53]
Imagine someone has data on existing networks as a .geojson file. They want to use the tool to design interventions to join gaps in existing networks. If they could upload .geojson files via an Upload GeoJSON button that could be really handy.

**Comment by robinlovelace-ate** [comment]
This is done :tada:

**Comment by robinlovelace-ate** [comment]
Yeah good point. I *think* ATIP can upload arbitrary .geojson files but not sure and also the UX/docs make no mention of it. Should there be a separate button? I suspect the single load .GeoJSON button can work for all use cases and we would need to test a wide range of inputs. That's a big job, I assumed it was just the uploading ATIP data one because it's V1 but potentially huge issue. Will reopen and set for V2 for now.

**Comment by dabreegster** [comment]
There's no support for loading arbitrary pre-drawn GJ in the scheme sketcher. Closing as not planned, but may revisit based on possible future users
