### ISSUE TITLE
Add buffer around all transport authorities

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#73]
New feature request from a user:

> Currently boundaries in ATIP are somewhat coarse and cut through a route, making it impossible to map it. Could you make sure the boundaries in ATIP at least have a buffer beyond the LA boundaries, particularly on the coast?

My thinking: this is reasonable, doable and would have benefits. Question: would the developer time cost outweigh the benefits? I'm happy to take a look at re-creating buffered boundaries.

**Comment by dabreegster** [comment]
https://github.com/acteng/abstreet-to-atip/pull/5 is related. Besides looking at the coast more carefully, any specific requests (that might suggest a buffer size)?

And longer-term, to get away from fixed boundaries for routing, see https://github.com/dabreegster/route_snapper/issues/7

**Comment by robinlovelace-ate** [comment]
Starter for 10: 500m or 1km could be good. Seems most relevant around coast but a small buffer could help encourage inter-authority schemes which is good.

Would 1km have any substantial performance impacts? I suggest that as a simple default if not.

**Comment by dabreegster** [comment]
Could try https://turfjs.org/docs/#buffer with https://github.com/acteng/abstreet-to-atip/blob/51a4003d385322d9018e51eb379e38437205f1ed/fix_boundaries/index.js#L9 and check file size impact (a proxy for load time)

**Comment by robinlovelace-ate** [comment]
Sounds sensible. Quickest way for me would be to simply create an alternative transport_authorities_buffered.geojson file with R. Keen to learn turfjs, at some point!

**Comment by Pecklett** [comment]
Apologies Robin/Dustin - when I asked for this I recalled the problem from an older version of ATIP (when I couldn't plot certain routes because the LA mask overlapped with sections of the road network) but I see under v1 there's a decent buffer, though I imagine there may still be places where LCWIP routes travel far into neighbouring authority areas.

**Comment by Robinlovelace** [comment]
Thanks for the feedback @Pecklett, sounds like this is a lower priority that what it was. Reasons for keeping it unchanged:

- You can always switch to 'non-snapping' mode when plotting routes by tapping shift, mitigating the impact for cross-authority schemes
- Having a buffer could lead to confusion about where boundaries are

So this enhancement would add a bit of confusion. I'm going to close for now because it's not in scope for v1 and may be fixed upstream in https://github.com/dabreegster/route_snapper/issues/7

Happy for it to be reopened/revisited later down the line.
