### ISSUE TITLE
GeoJSON from ATIP cannot be read with GDAL

### ISSUE THREAD

**Issue by robinlovelace-ate** [acteng/atip#86]
I tried reading a file from ATIP wth GDAL via R and got this error message:

```
leeds_from_atip = sf::st_read("leeds-from-atip.geojson")
Reading layer `leeds_cleaned' from data source `/home/robin/github/acteng/cycle_infra_quality/leeds-from-atip.geojson' using driver `GeoJSON'
Error in CPL_get_z_range(obj, 2) : z error - expecting three columns;
```

Interestingly it seems the route imports fine into QGIS which is great:

![image](https://user-images.githubusercontent.com/122299965/221145831-9797c0ca-ce73-4550-8a2a-f3470fe1558b.png)

Not a big one but worth flagging. GeoJSON attached: https://gist.github.com/robinlovelace-ate/cb5aa13e6615cd76bb0e10d1d0aad4ee

Note: this may be a special case because the file contains interventions from a file that was created outside of ATIP.

**Comment by dabreegster** [comment]
There are 3D coordinates, with the z-axis set to 0. Looks like GDAL or the bindings have a problem with that. The file works fine in geojson.io.

This file doesn't work great in ATIP; the MultiLineString may be messing things up, and the sidebar has a lot of "Untitled null" entries. But as you pointed out, it has non-ATIP stuff, so that's kind of expected.

**Comment by robinlovelace-ate** [comment]
Agreed, this is an edge case. Now realise: it's due to unusual input that has 3 dimensions (including Z) for the coordinates. The behaviour of the multilinestring is odd, I tried to delete one of the LineStrings and it deleted them all. Fine by me as that's what I wanted!

**Comment by Robinlovelace** [comment]
This was not related to ATIP.
